import DocHeader from "@/components/doc/navbar";
import SlideBar from "@/components/doc/slider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white w-full">
      <div className="bg-white flex min-h-screen flex-col ">
      <DocHeader/>
    <div className="max-w-7xl mx-auto container flex-1 items-start md:grid md:grid-cols-[220px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10">
      <aside
        className={`fixed top-14 z-30 -ml-2 hidden h-[calc(100vh-3.5rem)] w-full shrink-0 overflow-y-auto border-r md:sticky md:block`}
      >
        <div className="relative overflow-hidden py-6 pr-6 lg:py-8">
          <SlideBar />
        </div>
      </aside>
      <main className="relative py-6 lg:gap-10 lg:py-8 xl:grid xl:grid-cols-[1fr_300px]">
        <div className="mx-auto w-full min-w-0">
            {children}
        </div>
      </main>
    </div>
  </div>
      </body>
    </html>
  );
}
