
import { redirect } from "next/navigation"; 
import type { Metadata } from "next";
import Header from "@/components/ui/navbar";
import { auth } from "@clerk/nextjs/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const { userId } = auth();

  if (!userId) {
    redirect("/sign-in");
  }

  return (
    <html lang="en">
      <body className="bg-[#0D1117]">
        <Header />
        {children}
      </body>
    </html>
  );
}
